version: '3'
services:
  database:
    image: postgres:latest

  django:
    build:
      context: .
      dockerfile: ./dockerfiles/django_dockerfile
    command: bash -c "cd PiServer && python manage.py makemigrations && python manage.py migrate && gunicorn PiServer.wsgi -b 0.0.0.0:8000"
    environment:
      - ISPROD=True
    volumes:
      - .:/src
    depends_on:
      - database
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
    volumes:
      - ./PiServer/PiServer/staticfiles:/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
